name: CI/CD Workflow

on:
  push:
    branches:
      - park  # "park" 브랜치에 푸시가 될 때 트리거
  pull_request:
    branches:
      - park  # "park" 브랜치로 PR이 생성되거나 업데이트될 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST_KEY }}
          username: ${{ secrets.USER }}
          script: |
            mkdir -p /home/ubuntu/${{ github.event.repository.name }}
            cd /home/ubuntu/${{ github.event.repository.name }}
            git pull origin park
            # 추가 작업(빌드, 설치 등)을 이곳에 추가할 수 있습니다.

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js  # Node.js 환경 설정 추가
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Node.js 버전을 설정

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
