name: CI/CD Workflow

on:
  push:
    branches:
      - park
  pull_request:
    branches:
      - park

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST_KEY }}
          username: ${{ secrets.USER }}
          script: |
            mkdir -p /home/ubuntu/${{ github.event.repository.name }}
            cd /home/ubuntu/${{ github.event.repository.name }}
            git pull origin park

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./  # 올바른 경로 설정

      - name: Run tests
        run: npm test
        working-directory: ./  # 테스트를 올바른 경로에서 실행
