name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]  # PR이 열릴 때, 업데이트될 때, 다시 열릴 때, 닫힐 때 트리거

jobs:
  check-pr-events:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행

    steps:
      - name: Checkout code  # 리포지토리 코드 가져오기
        uses: actions/checkout@v3

      - name: Check if PR is opened  # PR이 열렸을 때
        if: github.event.action == 'opened'
        run: echo "PR opened event is working correctly!"

      - name: Check if PR is updated  # PR이 업데이트되었을 때 (synchronize)
        if: github.event.action == 'synchronize'
        run: echo "PR updated (synchronize) event is working correctly!"

      - name: Check if PR is reopened  # PR이 다시 열렸을 때
        if: github.event.action == 'reopened'
        run: echo "PR reopened event is working correctly!"

      - name: Check if PR is closed  # PR이 닫혔을 때
        if: github.event.action == 'closed'
        run: echo "PR closed event is working correctly!"
