name: Simple Pull Request Workflow

# 워크플로우 트리거 설정 (pull_request 이벤트)
on:
  pull_request:
    types: [opened, synchronize, reopened]  # PR이 열릴 때, 업데이트될 때, 다시 열릴 때 실행

jobs:
  notify:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행

    steps:
      - name: Checkout code  # 리포지토리 코드 가져오기
        uses: actions/checkout@v3

      - name: Display message  # 간단한 메시지 출력
        run: echo "Pull Request Workflow is working correctly!"
